# coding: utf-8

"""
    Everestek Custom APIs

    Everestek customs APIs developed as micro-service extension.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from com.fineos.idam.petinsurance.api.management_api import router as ManagementApiRouter


from com.fineos.idam.petinsurance.pet.api.pets_api import router as PetsApiRouter

app = FastAPI(
    title="Everestek Custom APIs",
    description="Everestek customs APIs developed as micro-service extension.",
    version="1.0",
    root_path="/petinsurance/v1",
)

app.include_router(ManagementApiRouter)
app.include_router(PetsApiRouter)
