# coding: utf-8

"""
    Swagger Petstore

    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.fineos.idam.petinsurance.razorpay.client.pets_api import PetsApi  # noqa: E501


class TestPetsApi(unittest.TestCase):
    """PetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_pets(self) -> None:
        """Test case for create_pets

        Create a pet.  # noqa: E501
        """
        pass

    def test_list_pets(self) -> None:
        """Test case for list_pets

        List all pets.  # noqa: E501
        """
        pass

    def test_show_pet_by_id(self) -> None:
        """Test case for show_pet_by_id

        Info for a specific pet.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
